<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MartiX.Specification.EntityFrameworkCore" Version="6.1.0" />
    <!-- <PackageReference Include="MartiX.EFCore.Extensions" Version="1.1.0" /> -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" PrivateAssets="all"
      Version="8.0.23" Condition="'$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" PrivateAssets="all"
      Version="10.0.2" Condition="'$(TargetFramework)' == 'net10.0'" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.23"
      Condition="'$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2"
      Condition="'$(TargetFramework)' == 'net10.0'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\MartiX.HttpClientTestExtensions.Core\MartiX.HttpClientTestExtensions.Core.csproj" />
    <ProjectReference
      Include="..\MartiX.HttpClientTestExtensions.SharedKernel\MartiX.HttpClientTestExtensions.SharedKernel.csproj" />
  </ItemGroup>

</Project>